window.NameForge=window.NameForge||{};
(function(){
 const C=window.NameForgePageConfig||{};
 const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
 const $=s=>document.querySelector(s);
 function init(){
  document.title=C.title+' | NameForge';
  const meta=document.querySelector('meta[name="description"]'); if(meta) meta.content=C.meta||C.description||'';
  document.body.innerHTML=`<header><nav class="container"><a href="index.html" class="logo"><span class="logo-icon">⚡</span>NameForge</a><div class="nav-links"><a href="index.html">Home</a><a href="all-name-generators.html">All Generators</a><a class="my-names" href="my-names.html">My Names</a><a href="#faq">FAQ</a></div></nav></header><main><section class="hero container"><span class="badge">${esc(C.badge||'⚡ FREE NAME GENERATOR')}</span><h1>${esc(C.h1a||'Forge your')} <span class="gradient">${esc(C.h1b||C.title)}</span></h1><p>${esc(C.description||'Generate unique names instantly with NameForge.')}</p><div class="hero-actions"><a class="btn" href="#generator">✨ Generate Names</a></div></section><section class="container generator-section" id="generator"><div class="generator"><div class="generator-header"><h2>${esc(C.icon||'✨')} ${esc(C.generatorTitle||C.title)}</h2><p class="generator-subtitle">${esc(C.generatorSubtitle||'Choose a style and length to generate unique names.')}</p></div><div class="controls"><select id="style"></select><select id="length"><option value="short">Short</option><option value="medium" selected>Medium</option><option value="long">Long</option></select><button class="generate" id="generateBtn">✨ Generate Names</button></div><div id="results" class="results"></div></div></section><section class="section" id="guide"><div class="content"><h2>${esc(C.guideTitle||'What is a name generator?')}</h2>${(C.guide||[]).map(x=>`<h3>${esc(x.h)}</h3><p>${esc(x.p)}</p>`).join('')}</div></section><section class="section container"><div class="content"><h2>${esc(C.cardsTitle||'Popular styles')}</h2></div><div class="cards">${(C.cards||[]).map(x=>`<div class="card"><h3>${esc(x.icon||'✨')} ${esc(x.h)}</h3><p>${esc(x.p)}</p></div>`).join('')}</div></section><section class="section container" id="faq"><div class="content"><h2>${esc(C.faqTitle||C.title+' FAQ')}</h2><div class="faq">${(C.faq||[]).map(x=>`<details><summary>${esc(x.q)}</summary><p>${esc(x.a)}</p></details>`).join('')}</div></div></section><section class="section container"><div class="content"><h2>Explore more NameForge generators</h2><div class="more-links">${(C.more||[]).map(x=>`<a href="${esc(x.href)}">${esc(x.label)}</a>`).join('')}</div></div></section></main><footer><div class="container"><strong>⚡ NameForge</strong><br><br>${esc(C.footer||'Free name generator for characters, stories, games and fictional worlds.')}<br><br>© 2026 NameForge</div></footer>`;
  const styleData=C.styles||window.NameForgeData?.[C.generator]||{};
  const select=$('#style'); Object.entries(styleData).forEach(([k,v])=>{if(k==='default'&&Object.keys(styleData).length>1)return;const o=document.createElement('option');o.value=k;o.textContent=`${v.icon||'✨'} ${v.label||k}`;select.appendChild(o)});
  if(!select.options.length){const o=document.createElement('option');o.value='default';o.textContent='✨ Default';select.appendChild(o)}
  const render=()=>{const style=select.value,length=$('#length').value;const items=NameForge.generate({generator:C.generator,style,length,quantity:9});NameForge.render($('#results'),items,{generator:C.generator,style,refresh:render})};
  $('#generateBtn').addEventListener('click',render); select.addEventListener('change',render); $('#length').addEventListener('change',render); render();
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();