window.NameForge=window.NameForge||{};
(function(){
 const C=window.NameForgePageConfig||{};
 const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
 const $=s=>document.querySelector(s);
 function init(){
  document.title=C.title+' | NameForge';
  const meta=document.querySelector('meta[name="description"]');if(meta)meta.content=C.meta||C.description||'';
  document.body.innerHTML=`<header><nav class="container"><a href="index.html" class="logo"><span class="logo-icon">⚡</span>NameForge</a><div class="nav-links"><a href="index.html">Home</a><a href="all-name-generators.html">Generators</a><a href="my-names.html">My Names</a><a href="#faq">FAQ</a></div></nav></header><main><section class="hero container"><span class="badge">${esc(C.badge||'⚡ FREE NAME GENERATOR')}</span><h1>${esc(C.h1a||'Forge your')} <span class="gradient">${esc(C.h1b||C.title)}</span></h1><p>${esc(C.description||'Generate unique names instantly with NameForge.')}</p><div class="hero-actions"><a class="btn" href="#generator">✨ Generate Names</a></div></section><section class="container generator-section" id="generator"><div class="generator"><div class="generator-header"><h2>${esc(C.icon||'⚔️')} ${esc(C.generatorTitle||C.title)}</h2><p class="generator-subtitle">${esc(C.generatorSubtitle||'Choose a style, length, format and gender to forge unique names instantly.')}</p></div><div class="controls controls-5"><select id="style"></select><select id="length"><option value="short">Short</option><option value="medium" selected>Medium</option><option value="long">Long</option></select><select id="format"><option value="title">🏷️ Titre pseudo / unique</option><option value="full">👤 Prénom et nom</option><option value="group">🏰 Clan / Royaume / Guilde</option></select><select id="gender"><option value="any">⚥ Any</option><option value="female">♀ Female</option><option value="male">♂ Male</option></select><button class="generate" id="generateBtn">✨ Generate Names</button></div><div id="results" class="results"></div></div></section><section class="section" id="guide"><div class="content"><h2>${esc(C.guideTitle||'What is a name generator?')}</h2>${(C.guide||[]).map(x=>`<h3>${esc(x.h)}</h3><p>${esc(x.p)}</p>`).join('')}</div></section><section class="section container"><div class="content"><h2>${esc(C.cardsTitle||'Popular styles')}</h2></div><div class="cards">${(C.cards||[]).map(x=>`<div class="card"><h3>${esc(x.icon||'✨')} ${esc(x.h)}</h3><p>${esc(x.p)}</p></div>`).join('')}</div></section><section class="section container" id="faq"><div class="content"><h2>${esc(C.faqTitle||C.title+' FAQ')}</h2><div class="faq">${(C.faq||[]).map(x=>`<details><summary>${esc(x.q)}</summary><p>${esc(x.a)}</p></details>`).join('')}</div></div></section></main><footer><div class="container"><strong>⚡ NameForge</strong><br><br>${esc(C.footer||'Free name generator for characters, stories, games and fictional worlds.')}<br><br>© 2026 NameForge</div></footer>`;
  const data=window.NameForgeData||{};const select=$('#style');
  NameForgeStyles.getOptions().forEach(o=>{const el=document.createElement('option');el.value=o.key;el.textContent=o.label;select.appendChild(el);});
  function render(){const options={generator:C.generator,style:select.value,length:$('#length').value,format:$('#format').value,gender:$('#gender').value,quantity:9};const items=NameForge.generate(options);NameForge.render($('#results'),items,{generator:C.generator,style:select.value,refresh:render});}
  $('#generateBtn').addEventListener('click',render);[select,$('#length'),$('#format'),$('#gender')].forEach(x=>x.addEventListener('change',render));render();
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();