window.NameForge=window.NameForge||{};
(function(){
 const C=window.NameForgePageConfig||{};
 const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
 const $=s=>document.querySelector(s);

 const DETAILS={
  anime:{title:"What is an anime name generator?",intro:"A creative naming tool for anime-inspired characters, designed to help writers, players and creators build memorable identities quickly.",cards:[["📖","Built for character creation","Create names suited to protagonists, rivals, warriors, villains, school characters and supernatural heroes."],["🎌","Inspired by anime naming styles","The generator combines different archetypes and linguistic patterns to produce names that feel coherent with anime-inspired worlds."],["🎮","Made for stories and games","Use generated names for original characters, manga-inspired projects, RPG campaigns, games, fan projects and worldbuilding."],["✨","21 styles to explore","Switch between heroic, dark, royal, mystical, warrior and other archetypes to change the identity of the generated character."]],steps:["Choose an anime style","Set length, format and gender","Generate, save, like or copy your favorite names"]},
  dragon:{title:"What is a dragon name generator?",intro:"A fantasy naming tool designed to create powerful draconic identities for ancient dragons, dragonkin, wyrms and legendary creatures.",cards:[["🐉","Built for draconic characters","Create names for dragons, dragonkin, wyrms, ancient beasts and legendary creatures."],["🔥","Powerful fantasy sounds","NameForge combines sharp, ancient and elemental naming patterns to give names a strong draconic identity."],["📚","Useful for worldbuilding","Create names for novels, RPG campaigns, games, stories, kingdoms and original fantasy universes."],["⚡","Control the identity","Choose among 21 styles, three lengths, three formats and gender options before generating."]],steps:["Choose a draconic archetype","Customize the name format","Generate and keep the names that fit your creature"]},
  elf:{title:"What is an elf name generator?",intro:"A fantasy naming tool for creating elegant, melodic and memorable names for elves and other high-fantasy characters.",cards:[["🧝","Elven-inspired identities","Create names suited to high elves, woodland elves, dark elves, rangers and ancient fantasy characters."],["🌿","Elegant naming patterns","The generator favors flowing combinations and fantasy-inspired sounds for a refined character identity."],["📖","For stories and RPGs","Use names for novels, games, tabletop campaigns, role-playing characters and worldbuilding."],["✨","Flexible generation","Use the 21 shared NameForge styles alongside length, format and gender controls."]],steps:["Pick the style that matches your elf","Choose length and naming format","Generate several options and save your favorites"]},
  gaming:{title:"What is a gaming name generator?",intro:"A fast naming tool for players who need memorable identities, usernames and character names for games and online worlds.",cards:[["🎮","Made for gamers","Generate names for characters, profiles, teams, clans and fictional identities."],["⚡","Fast and varied","Create multiple options at once instead of repeatedly inventing names manually."],["🏆","Different gaming identities","Switch between heroic, dark, royal, mystical, warrior and other styles depending on your game."],["📋","Easy to keep","Copy a name instantly or use NameForge's save and like tools to build your personal collection."]],steps:["Select your gaming style","Choose the desired name structure","Generate and shortlist your best identities"]},
  kingdom:{title:"What is a kingdom name generator?",intro:"A worldbuilding tool for creating names for kingdoms, realms, empires, clans and fictional territories.",cards:[["👑","Build fictional realms","Generate names that can become the foundation of a kingdom, empire or fantasy territory."],["🏰","Designed for worldbuilding","Useful for authors, game designers, Dungeon Masters and creators building original universes."],["🗺️","Create a coherent world","Use different naming styles to distinguish noble kingdoms, dark realms, ancient lands and powerful empires."],["✨","Customize the result","Control the length, format, style and gender settings to match the type of identity you need."]],steps:["Choose the realm's style","Select the desired structure and length","Generate names for your map, lore or campaign"]},
  rpg:{title:"What is an RPG name generator?",intro:"A character naming tool built for role-playing games, tabletop campaigns and fantasy adventures.",cards:[["🎲","Made for RPG characters","Create names for heroes, companions, villains, NPCs, warriors, mages and other adventurers."],["⚔️","Fits different archetypes","Use the 21 styles to quickly move from heroic and noble to dark, mystical or dangerous identities."],["📜","Useful for campaigns","Great for D&D-style campaigns, tabletop adventures, role-playing stories and original RPG worlds."],["💾","Keep your discoveries","Generate several candidates, then save, like, rate or copy the names you want to remember."]],steps:["Choose the character archetype","Define the name structure","Generate candidates and choose the one that fits your character"]},
  "sci-fi":{title:"What is a sci-fi name generator?",intro:"A futuristic naming tool for creating identities suited to space operas, cyberpunk worlds, colonies, alien characters and science-fiction stories.",cards:[["🚀","Built for futuristic worlds","Generate names for pilots, soldiers, scientists, explorers, aliens and original sci-fi characters."],["🪐","Futuristic identity patterns","Combine modern, technological and speculative naming ideas for a distinct science-fiction feel."],["🎮","For games and stories","Use generated names in novels, games, RPG campaigns, comics, worldbuilding and fictional universes."],["✨","Control the tone","Choose among 21 styles plus length, format and gender options to refine the identity."]],steps:["Choose the futuristic style","Set the length and name format","Generate and keep the strongest candidates"]},
  vampire:{title:"What is a vampire name generator?",intro:"A dark fantasy naming tool for creating elegant, mysterious and memorable identities for vampires and gothic characters.",cards:[["🦇","Gothic character identities","Create names for vampires, nobles, immortals, hunters and supernatural characters."],["🌙","Elegant and dark tones","Choose styles that create refined, mysterious, ancient or sinister character identities."],["📖","Perfect for dark fiction","Useful for novels, games, RPG campaigns, comics and supernatural worldbuilding."],["🩸","Shape the character","Use length, format, gender and 21 style options to control the tone of the result."]],steps:["Choose the vampire archetype","Define the name structure","Generate and save the names that fit your character"]},
  warrior:{title:"What is a warrior name generator?",intro:"A character naming tool for heroes, fighters, soldiers, champions and legendary warriors across fantasy and gaming worlds.",cards:[["⚔️","Built for warriors","Generate names for fighters, knights, champions, mercenaries and legendary battle characters."],["🛡️","Strong character identities","Choose heroic, royal, dark, ancient and other styles to match the warrior's role."],["🎲","For RPGs and stories","Use names for tabletop campaigns, games, novels, comics and original fantasy worlds."],["🔥","Customize the result","Control length, format, gender and style before generating a new set of names."]],steps:["Choose the warrior archetype","Set length, format and gender","Generate and select the strongest identity"]},
  wizard:{title:"What is a wizard name generator?",intro:"A magical naming tool for creating memorable identities for wizards, mages, sorcerers and arcane characters.",cards:[["📜","Built for magic users","Create names for wizards, mages, sorcerers, archmages, apprentices and mystical characters."],["🔮","Arcane naming styles","Choose styles that suggest ancient knowledge, elemental power, dark magic or celestial mystery."],["✍️","Useful for creators","Ideal for novels, RPG campaigns, games, comics and fantasy worldbuilding."],["✨","Fine-tune the identity","Use 21 styles, three lengths, three formats and gender options to refine each result."]],steps:["Select the magical archetype","Choose the name structure and length","Generate several names and keep the best fit"]}
 };
 const FALLBACK={title:"What is a NameForge name generator?",intro:"A professional creative naming tool designed to help you create memorable fictional identities for characters, stories, games and worldbuilding.",cards:[["🧩","Creative name construction","Combine style, length and naming structure to create coherent fictional identities."],["🎯","Designed for creators","Useful for writers, players, game designers and anyone building an original fictional world."],["⚙️","Flexible controls","Choose a style, length, format and gender before generating your names."],["💾","Keep your favorites","Save, like, rate and copy the names that you want to remember."]],steps:["Choose your preferred style","Customize the generation options","Generate and keep your favorite names"]};

 function renderDetails(key){
  const D=DETAILS[key]||FALLBACK;
  const generatorSection=document.querySelector('#generator');
  if(!generatorSection||document.querySelector('#professional-details')) return;
  const section=document.createElement('section');section.className='section professional-details';section.id='professional-details';
  section.innerHTML=`<div class="container"><div class="details-intro"><span class="details-eyebrow">✨ ABOUT THIS GENERATOR</span><h2>${esc(D.title)}</h2><p>${esc(D.intro)}</p></div><div class="details-grid">${D.cards.map(x=>`<article class="detail-card"><div class="detail-icon">${esc(x[0])}</div><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></article>`).join('')}</div><div class="details-how"><div><span class="details-eyebrow">⚙️ HOW IT WORKS</span><h3>Create a name in three simple steps</h3></div><div class="steps">${D.steps.map((x,i)=>`<div class="step"><span>${i+1}</span><div><strong>${esc(x)}</strong><p>${i===0?'Start by selecting the identity or archetype that best matches your project.':i===1?'Adjust the controls to get the structure and tone you want.':'Generate multiple results and keep the names that best fit your character or world.'}</p></div></div>`).join('')}</div></div></div>`;
  generatorSection.insertAdjacentElement('afterend',section);
 }

 function init(){
  document.title=C.title+' | NameForge';
  const meta=document.querySelector('meta[name="description"]');if(meta)meta.content=C.meta||C.description||'';
  document.body.innerHTML=`<header><nav class="container"><a href="index.html" class="logo"><span class="logo-icon">⚡</span>NameForge</a><div class="nav-links"><a href="index.html">Home</a><a href="all-name-generators.html">Generators</a><a href="my-names.html">My Names</a><a href="#faq">FAQ</a></div></nav></header><main><section class="hero container"><span class="badge">${esc(C.badge||'⚡ FREE NAME GENERATOR')}</span><h1>${esc(C.h1a||'Forge your')} <span class="gradient">${esc(C.h1b||C.title)}</span></h1><p>${esc(C.description||'Generate unique names instantly with NameForge.')}</p><div class="hero-actions"><a class="btn" href="#generator">✨ Generate Names</a></div></section><section class="container generator-section" id="generator"><div class="generator"><div class="generator-header"><h2>${esc(C.icon||'⚔️')} ${esc(C.generatorTitle||C.title)}</h2><p class="generator-subtitle">${esc(C.generatorSubtitle||'Choose a style, length, format and gender to forge unique names instantly.')}</p></div><div class="controls controls-5"><select id="style"></select><select id="length"><option value="short">Short</option><option value="medium" selected>Medium</option><option value="long">Long</option></select><select id="format"><option value="title">🏷️ Titre pseudo / unique</option><option value="full">👤 Prénom et nom</option><option value="group">🏰 Clan / Royaume / Guilde</option></select><select id="gender"><option value="any">⚥ Any</option><option value="female">♀ Female</option><option value="male">♂ Male</option></select><button class="generate" id="generateBtn">✨ Generate Names</button></div><div id="results" class="results"></div></div></section><section class="section" id="guide"><div class="content"><h2>${esc(C.guideTitle||'What is a name generator?')}</h2>${(C.guide||[]).map(x=>`<h3>${esc(x.h)}</h3><p>${esc(x.p)}</p>`).join('')}</div></section><section class="section container"><div class="content"><h2>${esc(C.cardsTitle||'Popular styles')}</h2></div><div class="cards">${(C.cards||[]).map(x=>`<div class="card"><h3>${esc(x.icon||'✨')} ${esc(x.h)}</h3><p>${esc(x.p)}</p></div>`).join('')}</div></section><section class="section container" id="faq"><div class="content"><h2>${esc(C.faqTitle||C.title+' FAQ')}</h2><div class="faq">${(C.faq||[]).map(x=>`<details><summary>${esc(x.q)}</summary><p>${esc(x.a)}</p></details>`).join('')}</div></div></section></main><footer><div class="container"><strong>⚡ NameForge</strong><br><br>${esc(C.footer||'Free name generator for characters, stories, games and fictional worlds.')}<br><br>© 2026 NameForge</div></footer>`;
  const select=$('#style');NameForgeStyles.getOptions().forEach(o=>{const el=document.createElement('option');el.value=o.key;el.textContent=o.label;select.appendChild(el);});
  function render(){const options={generator:C.generator,style:select.value,length:$('#length').value,format:$('#format').value,gender:$('#gender').value,quantity:9};const items=NameForge.generate(options);NameForge.render($('#results'),items,{generator:C.generator,style:select.value,refresh:render});}
  $('#generateBtn').addEventListener('click',render);[select,$('#length'),$('#format'),$('#gender')].forEach(x=>x.addEventListener('change',render));render();renderDetails(C.generator);
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();